INSERT INTO menu (name, price, image, description, category_id) VALUES
('Tomato Basil Soup', 4.99, 'images/tomato_basil_soup.jpg', 'Rich and creamy tomato soup with fresh basil.', '8'),
('Chicken Noodle Soup', 5.99, 'images/chicken_noodle_soup.jpg', 'Classic chicken noodle soup with tender chicken and fresh vegetables.', '8'),
('Minestrone Soup', 5.49, 'images/minestrone_soup.jpg', 'Hearty vegetable soup with beans, pasta, and fresh herbs.', '8'),
('Butternut Squash Soup', 6.49, 'images/butternut_squash_soup.jpg', 'Creamy butternut squash soup with a hint of nutmeg.', '8'),
('French Onion Soup', 6.99, 'images/french_onion_soup.jpg', 'Rich beef broth with caramelized onions and melted cheese on top.', '8'),
('Broccoli Cheddar Soup', 5.99, 'images/broccoli_cheddar_soup.jpg', 'Creamy soup with fresh broccoli and sharp cheddar cheese.', '8'),
('Lentil Soup', 4.99, 'images/lentil_soup.jpg', 'Hearty lentil soup with carrots, celery, and spices.', '8'),
('Potato Leek Soup', 5.49, 'images/potato_leek_soup.jpg', 'Smooth and creamy potato soup with leeks and a hint of garlic.', '8'),
('Clam Chowder', 6.99, 'images/clam_chowder.jpg', 'Rich and creamy clam chowder with tender clams and potatoes.', '8'),
('Beef Barley Soup', 6.49, 'images/beef_barley_soup.jpg', 'Hearty beef and barley soup with fresh vegetables.', '8'),
('Cream of Mushroom Soup', 5.99, 'images/cream_of_mushroom_soup.jpg', 'Smooth and creamy mushroom soup with a hint of thyme.', '8'),
('Split Pea Soup', 4.99, 'images/split_pea_soup.jpg', 'Thick and hearty split pea soup with ham and vegetables.', '8'),
('Vegetable Soup', 4.49, 'images/vegetable_soup.jpg', 'Healthy and hearty vegetable soup with a variety of fresh vegetables.', '8'),
('Corn Chowder', 5.49, 'images/corn_chowder.jpg', 'Creamy corn chowder with sweet corn and potatoes.', '8'),
('Chicken Tortilla Soup', 6.49, 'images/chicken_tortilla_soup.jpg', 'Spicy chicken tortilla soup with black beans and corn.', '8'),
('Pumpkin Soup', 5.99, 'images/pumpkin_soup.jpg', 'Creamy pumpkin soup with a hint of cinnamon and nutmeg.', '8'),
('Seafood Bisque', 7.49, 'images/seafood_bisque.jpg', 'Rich and creamy seafood bisque with shrimp, crab, and lobster.', '8'),
('Gazpacho', 5.49, 'images/gazpacho.jpg', 'Chilled tomato soup with fresh cucumbers, bell peppers, and onions.', '8'),
('Chicken and Rice Soup', 5.99, 'images/chicken_rice_soup.jpg', 'Hearty chicken and rice soup with fresh vegetables.', '8'),
('Tom Yum Soup', 6.99, 'images/tom_yum_soup.jpg', 'Spicy Thai soup with shrimp, mushrooms, and lemongrass.', '8');
