INSERT INTO menu (name, price, image, description, category_id) VALUES
('Spicy Tuna Roll', 12.99, 'https://www.example.com/spicy-tuna-roll.jpg', 'Classic spicy tuna roll with avocado and sriracha mayo.', 9),
('California Roll', 10.99, 'https://www.example.com/california-roll.jpg', 'Cream cheese, crabmeat, cucumber, and avocado wrapped in soy paper.', 9),
('Philadelphia Roll', 11.99, 'https://www.example.com/philadelphia-roll.jpg', 'Smoked salmon, cream cheese, and cucumber rolled in soy paper.', 9),
('Rainbow Roll', 13.99, 'https://www.example.com/rainbow-roll.jpg', 'Spicy tuna, avocado, cucumber, and tobiko wrapped in soy paper.', 9),
('Dragon Roll', 14.99, 'https://www.example.com/dragon-roll.jpg', 'Tempura shrimp, avocado, cucumber, and eel sauce.', 9),
('Spider Roll', 15.99, 'https://www.example.com/spider-roll.jpg', 'Soft-shell crab, cucumber, avocado, and spicy mayo.', 9),
('Eel Avocado Roll', 12.99, 'https://www.example.com/eel-avocado-roll.jpg', 'Freshwater eel, avocado, and eel sauce.', 9),
('Salmon Avocado Roll', 11.99, 'https://www.example.com/salmon-avocado-roll.jpg', 'Fresh salmon, avocado, and cucumber.', 9),
('Yellowtail Scallion Roll', 13.99, 'https://www.example.com/yellowtail-scallion-roll.jpg', 'Yellowtail, scallions, and a touch of ponzu sauce.', 9),
('Tuna Tataki', 16.99, 'https://www.example.com/tuna-tataki.jpg', 'Seared tuna, ponzu sauce, and sesame seeds.', 9),
('Salmon Sashimi', 14.99, 'https://www.example.com/salmon-sashimi.jpg', 'Thinly sliced fresh salmon served with soy sauce, wasabi, and pickled ginger.', 9),
('Tuna Sashimi', 15.99, 'https://www.example.com/tuna-sashimi.jpg', 'Thinly sliced fresh tuna served with soy sauce, wasabi, and pickled ginger.', 9),
('Maki Roll', 9.99, 'https://www.example.com/maki-roll.jpg', 'Simple cucumber and avocado roll.', 9),
('Spicy Salmon Roll', 12.99, 'https://www.example.com/spicy-salmon-roll.jpg', 'Salmon, avocado, and sriracha mayo.', 9),
('Shrimp Tempura Roll', 13.99, 'https://www.example.com/shrimp-tempura-roll.jpg', 'Tempura shrimp, avocado, and cucumber.', 9),
('Spicy Crab Roll', 11.99, 'https://www.example.com/spicy-crab-roll.jpg', 'Spicy crabmeat, avocado, and cucumber.', 9),
('Unagi Roll', 14.99, 'https://www.example.com/unagi-roll.jpg', 'Eel, cucumber, and avocado.', 9),
('Salmon Skin Roll', 12.99, 'https://www.example.com/salmon-skin-roll.jpg', 'Crispy salmon skin, cucumber, and avocado.', 9),
('Spicy Tuna Hand Roll', 8.99, 'https://www.example.com/spicy-tuna-hand-roll.jpg', 'Spicy tuna and avocado wrapped in nori.', 9),
('California Hand Roll', 7.99, 'https://www.example.com/california-hand-roll.jpg', 'Crabmeat, cucumber, and avocado wrapped in nori.', 9);