services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_HOST: ${POSTGRESQL_HOST}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    
